### ISSUE TITLE
Perk-related Badges

### ISSUE THREAD

**Issue by JoePagano** [egoal/darkest-pixel-dungeon#10]
I completed the game without selecting any perks, and cleared out my starting perks (plus the free healing potion efficiency perk).

Neither of the perk-related badges (no perks selected, or complete the game with no perks at all) was marked as complete.

**Comment by egoal** [comment]
oh, did you get "happy ending" in this run? 
i mean, did you finished the game by exit the village (the 0 depth floor)? if the game was finished by using the amulet, then the badges cannot be triggered.

**Comment by JoePagano** [comment]
I did not, didn't realize that.

**Comment by egoal** [comment]
then that's the cause. :)
