### ISSUE TITLE
Game crashed :(

### ISSUE THREAD

**Issue by Norberteo** [egoal/darkest-pixel-dungeon#11]
So i somehow corrupted my game file. I got cornered by 2 evil eyes and a scubbus on floor 23. I drinked a potion of breathing then threw paralysis one and walked top right quickly after. My game crashed and now im stuck on floor 22 since when i try to go deeper the error message appears again and well there goes my run.

**Comment by egoal** [comment]
thanks for your reply.
which version are you playing. could you please upload the crash log? you can find a blinking '!' at the bottom right in the title scene if the last run was crashed, click on it. :-)

**Comment by Norberteo** [comment]
![IMG_20210704_182710](https://user-images.githubusercontent.com/86794428/124392397-a0ee4480-dcf5-11eb-8b97-a6a1a7f63fe9.png)
Here ya go! Hope it gets fixed, it was my 1st run too.

**Comment by egoal** [comment]
thanks for the post! i'll check and try fix it in the next version.
