### ISSUE TITLE
Mask of madness issue

### ISSUE THREAD

**Issue by Xazmadan** [egoal/darkest-pixel-dungeon#12]
somewhy while playing with evil greed challenge and wearing mask madness +10 stepping on any unfound trap instantly kill you, even while trap isn't do any damage, like confusion gas trap or treasure trap

**Comment by Xazmadan** [comment]
it isn't do any crash reports or blinking !, just  instant death, on the moment i has 3 mental damage and full hp(100) played as sorceress reclassed to astral gazer

**Comment by egoal** [comment]
oh, this is surly weird, thanks for the reply i'll check it later.
