### ISSUE TITLE
0 damage critical hist still apply stress damage

### ISSUE THREAD

**Issue by Xazmadan** [egoal/darkest-pixel-dungeon#14]
i noticed what any monster with high crit chance can crit by 0, and still apply stress damage, while players crits in certain situations can too be about zero but relieve stress, it is looking strange lol, while instakill crits sometimes not apply any relieve and common monster hits which do a significant damage about 30% hp isnt apply any stress

**Comment by egoal** [comment]
this was changed in 0.6.1: any damage less than 1 wont apply stress damage now.
