### ISSUE TITLE
issue with war flag desc on english

### ISSUE THREAD

**Issue by Xazmadan** [egoal/darkest-pixel-dungeon#19]
![Screenshot_2022-09-23-14-47-10-009_com.egoal.darkestpixeldungeon.jpg](https://user-images.githubusercontent.com/69046303/191953797-902e3e56-bc61-4e12-aad9-e71cf49a9d7b.jpg)

**Comment by egoal** [comment]
yeah, this is caused by the untranslated Chinese ancient poem.

I may just remove the poem in other translation.
