### ISSUE TITLE
critical chance over 100%

### ISSUE THREAD

**Issue by Xazmadan** [egoal/darkest-pixel-dungeon#20]
![Screenshot_2022-09-23-16-49-00-572_com.egoal.darkestpixeldungeon.jpg](https://user-images.githubusercontent.com/69046303/191975560-83fd855a-318b-40b9-b7ef-fea406576aa4.jpg)![Screenshot_2022-09-23-16-49-03-249_com.egoal.darkestpixeldungeon.jpg](https://user-images.githubusercontent.com/69046303/191975572-35621400-ee52-4e9e-8ff6-3f19b33d6594.jpg)![Screenshot_2022-09-23-16-48-21-011_com.egoal.darkestpixeldungeon.jpg](https://user-images.githubusercontent.com/69046303/191975579-4970876e-cb9e-4d10-86c6-dd1acfe76420.jpg)

**Comment by egoal** [comment]
This may seem strange, but it's OK.
