### ISSUE TITLE
after resurrection with unblessed ankh evil greed stops recharging making hero unable to receive gold

### ISSUE THREAD

**Issue by Xazmadan** [egoal/darkest-pixel-dungeon#23]
![Screenshot_2022-09-27-10-23-05-134_com.egoal.darkestpixeldungeon.jpg](https://user-images.githubusercontent.com/69046303/192603537-608f574d-f1f0-4074-8720-c56064a7bb3c.jpg)![Screenshot_2022-09-27-10-23-09-605_com.egoal.darkestpixeldungeon.jpg](https://user-images.githubusercontent.com/69046303/192603562-a38c8678-30d2-49ba-b0a4-5887683a839e.jpg)
just imagine get this bug on 6 floor lmao

**Comment by egoal** [comment]
just fixed it, 

in the next release.
