### ISSUE TITLE
critical bug extraction flask

### ISSUE THREAD

**Issue by Xazmadan** [egoal/darkest-pixel-dungeon#24]
while improved extraction flask purifying water it cant be active from inventory, while still can be activated to refine from the hotbar![Screenshot_2022-10-03-13-46-45-993_com.egoal.darkestpixeldungeon.jpg](https://user-images.githubusercontent.com/69046303/193559883-a6b7d507-2fea-4301-a4b5-483701fac0a9.jpg)![Screenshot_2022-10-03-13-46-42-856_com.egoal.darkestpixeldungeon.jpg](https://user-images.githubusercontent.com/69046303/193559892-ba7f0245-09a9-443d-9752-da22e73366c7.jpg)

**Comment by egoal** [comment]
this already fixed in current code.
