### ISSUE TITLE
Minor Issue with boss doors

### ISSUE THREAD

**Issue by Omnipresent4ce** [egoal/darkest-pixel-dungeon#7]
There are 2 boss doors I have discovered unintended situations to occur with.
1- Tengu door- This one is reliant on a wand of corruption and telepathy perk.
Bringing a corrupted minion to said entry door, once entering and selecting swap places with companion will leave one permanently locked out and unable to continue game file. Maybe have Tengu battle activation kill corrupted companions or blackout entry hallway(like despising a monster statue)
2- Dwarf King- Reliant upon possessing statue room key, one can unlock foyer after instigating dwarf king battle and sit there without consequence to heal, rebuild charges etc.
Although they wait just outside the door until you renter and you cannot attack from outside even with polearm/projecting weapons(have not tested ranged nor wands) and skeleton bodies while downed block projectiles and wands. Dwarf king will enter the room and skeletons are then able to access as well.

The second is an interesting egg as is as an alternative(if wands won't penetrate door) to receiving the blueprint as currently by my testing it has minimal beneficial effect in comparison(other than effectively safe healing/recharging)and consumes said key.

**Comment by Omnipresent4ce** [comment]
![Screenshot_20210119-115730](https://user-images.githubusercontent.com/75098600/105067402-a577b700-5a4d-11eb-8fa5-0acffbf1d493.png)
![Screenshot_20210119-115717](https://user-images.githubusercontent.com/75098600/105067417-a9a3d480-5a4d-11eb-8f1b-9e14d34421a7.png)
![Screenshot_20210119-115649](https://user-images.githubusercontent.com/75098600/105067423-ac062e80-5a4d-11eb-824c-43acdaf3bc89.png)

**Comment by Omnipresent4ce** [comment]
![Screenshot_20210119-115626](https://user-images.githubusercontent.com/75098600/105067645-e5d73500-5a4d-11eb-958d-299fe9b27947.png)

**Comment by Omnipresent4ce** [comment]
Also if you Hypnotize Tengu during his teleport/clone attack phase causing him to teleport and be asleep, the game mechanics do not recognize what is going on and one must return to menu as it is perpetually stuck processing said turn.

**Comment by egoal** [comment]
so, in the next versoin, 
1. when Tenge lock the door, the unit on the door pos would be placed to the left adjacent cell. however, if there;s no free space on that cell, it would be killed.
2. now, the King would set the door to a Wall instead. so the player cannot open the door with the iron key.
3. I've adjust Tengu's act timing. Now tengu would act on his turn (no longer jump away if you stop the time), this should also fixed the Hypnotize problem.
