### ISSUE TITLE
Eating a sunfruit causes the player's health to exceed the max health

### ISSUE THREAD

**Issue by MegaMinxUp** [egoal/darkest-pixel-dungeon#8]
I noticed a weird bug regarding the sunfruit (blandfruit cooked in sungrass seed) in which eating one heals the player by its max health, adding it to current health and results to the player's health being higher than the max health. The bug becomes somehow useful for a short period of time (until the extra health was lost). I also attached a screenshot showing the health bar after eating one. I hope that the bug gets fixed soon. Thanks in advance.
![Screenshot_2021-04-29-16-16-31](https://user-images.githubusercontent.com/78413094/116525764-6dfd8e00-a90b-11eb-9754-a6c3f8b33dc8.png)

**Comment by egoal** [comment]
thanks for the report. this is a feature however. 
eating a cooked fruit applys the strengthened version of the related potion. for the sunfruit, that is, reinfored Potion of Healing, which would heals the hero with his/her max health.
