### ISSUE TITLE
Incorrect Attack Speed - Yvette's Longbow

### ISSUE THREAD

**Issue by JoePagano** [egoal/darkest-pixel-dungeon#9]
Per the wiki, the long bow should be firing at 1 round/attack, but it appears to be 1.5 rounds/attack.

**Comment by egoal** [comment]
thanks for the report, I would check the info on wiki.
btw, refer to the code, it's 1.2 rounds per attack. ;-)

**Comment by JoePagano** [comment]
Got it, thanks
